### ISSUE TITLE
Not able to change a defined var - BetterLogic adds a new tag "logic" with temp variables

### ISSUE THREAD

**Issue by carmei** [PatrickSannes/BetterLogic#19]
Hi Patrick, tried to use BetterLogic to define a simple Heating Schedule ON/OFF status. Aim is to set the whole heating schedule to off if no one is at home. I created a Var - boolean "Heating Schedule Status" (i also tested it with "test"). Most of the time I need to drag the var out of the tag list, yesterday I was very surprised that I was able to select the var via drop down. This only worked one day ;-) Not sure why. But the point is, I am not able to change the boolean var neither to False or True via Set boolean var to ....
I setup a flow to test it and the tag list shows a new entry under "Logic" with a var named true - NO or False - Yes. I tried to use these ones without success. Yesterday it worked on the basis off the dropdown selection. But something changed today so that I am still at the beginning for such a simple flow. Not sure if I am the issue or homey or BetterLogic. Maybe it is known and not a bug. 
Thanks - Carsten

**Comment by PatrickSannes** [comment]
Sorry for the extreme late response. Probably you did not select the value in the drop down, but only typed it.. This is a known bug. These questions are better asked in the forhm so more people can answer when I'm busy with normal life ;)
