### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by lenwar** [PatrickSannes/BetterLogic#21]
Hi,

If at all possible ( I have no insight in how limiting the Homey APIs are) I would like to have a case-statement logic function.

I am running into the following
I use the Sunlight Events app to change my Hue Ambiance light brightness and color temperature.
I now have six different Flows:
- After Sunset, brightness is 0,8 and color is 0,6
- After Nightfall, brightness is 0,6 and color is 0,8
- Etc.

Ideally we would just have one Flow which runs a case-statement, when it is triggered and matches variables to other variables.

**Comment by PatrickSannes** [comment]
I don't think this is possible, because you still want different then actions. And those are limited. I think you should try using multiple flows for now..
