### ISSUE TITLE
Round incremented/decremented number to number of decimals

### ISSUE THREAD

**Issue by sschutten** [PatrickSannes/BetterLogic#24]
If for example I add 0.2 to a variable that is currently 0.7, the variable shows 0.8999999999999999. This is off course due to the floating point precision error. Unfortunately some devices are not able to use these values (e.g. the brightness of my Hue lights don't change if it has this many decimals) so it would be great to add the option to round to a specific number of decimals.

**Comment by lenwar** [comment]
As a workaround I am using a mathjs card in my'then' which effectively rounds up to two decimals:

round( VARIABLENAME * 100) / 100

(I'm using 100 as my hue lights swallow 0 - 1 with in/decrements of 0.01 ( I think?) ) If you need a finer resolution, you can 1000 or higher) I haven't tested that for Hue lights.

**Comment by sschutten** [comment]
That's an excellent workaround! It didn't occur to me that I could use the mathjs functions as well.

BTW, you can tell the round function to how many decimals you'd like to round, like this:
`round(VARIABLENAME, 2)`

**Comment by lenwar** [comment]
Glad it works for you :)

I recall I had issues with the `,2`-syntax. It didn't always return what I expected, but I don't recall under which circumstances.

Anyway... Happy to help :-)
