### ISSUE TITLE
After deletion of variables, Insights stay (for old var) and can not be deleted

### ISSUE THREAD

**Issue by jeroenvano** [PatrickSannes/BetterLogic#3]
When deleting values (or delete all) the insights stay and are not deleted. 
Would be nice to be able to delete old variables in Insights or to have a default setting when deleted also deletes Insights for this var.

**Comment by PatrickSannes** [comment]
This should have been the default behavior. I'll go check what is going on.

**Comment by PatrickSannes** [comment]
Fixed in release 0.9.7.

If you have leftovers from pre-fix. Backup -> deleteall -> restore or do it per variable (add, delete)
