### ISSUE TITLE
Access to 'Better Logic' variables and 'Homey' variables not consistent

### ISSUE THREAD

**Issue by LesPaul1962** [PatrickSannes/BetterLogic#31]
I have an ifttt event with a parameter [var1]. In the then of else I can access it via Better Logic, but not in the if/and/or. See flow.
![image](https://user-images.githubusercontent.com/13146572/47067698-893f9c80-d1ea-11e8-98a0-0081432edb27.png)

**Comment by PatrickSannes** [comment]
Is it a numeric value? Else try to cast with mathjs

**Comment by LesPaul1962** [comment]
Solved , see picture. Thanx
![image](https://user-images.githubusercontent.com/13146572/47077258-d62e6d80-d200-11e8-9daa-904e34544004.png)
