### ISSUE TITLE
Slider doesn't work after homey update 2.0

### ISSUE THREAD

**Issue by EdwardDumay** [PatrickSannes/BetterLogic#34]
I updated Homey to 2.0. I used I think you called it sliders. In fact you were able to change variables by this. Now you see that the column is changing but you don't see the value you are changing.

**Comment by PatrickSannes** [comment]
Tested it on my phone. The device type is changed to a dimmable type and
with the new homey it works a bit different. We now get back a value
between 0 and 1. This is stored. So min and max don't work.
I think we can fix the value, but we cannot fix that you see the number
(it's a homey device restriction)

**Comment by EdwardDumay** [comment]
The way it work was very usefull.
Now it  is not possible to view what the value is. I used it setting up a
night and day temperature for my thermostat with min value 10 degrees and
max 25 degrees. So as I understood this not possible anymore because of
restrictions in homey 2 version. If so I will contact Homey. Thanks for
your fast response.


Op wo 16 jan. 2019 10:00 schreef Patrick Sannes <notifications@github.com:

> Tested it on my phone. The device type is changed to a dimmable type and
> with the new homey it works a bit different. We now get back a value
> between 0 and 1. This is stored. So min and max don't work.
> I think we can fix the value, but we cannot fix that you see the number
> (it's a homey device restriction)
>

**Comment by SailingDuck** [comment]
Busy trying to fix it but can't get it to work. Reported an issue at the apps-sdk: https://github.com/athombv/homey-apps-sdk-issues/issues/42

Also requested to have the dimvalue optionally visbile. It is considered. 
https://github.com/athombv/homey-apps-sdk-issues/issues/18
Never hurts to contact Athom about your request :)

**Comment by EdwardDumay** [comment]
I had contact with Emile from support of Athom. He wrote that they were not aware of the limitations. And you are invited to talk with them about this issue.

**Comment by SailingDuck** [comment]
What limitations are you taking about? 

The slider not working or the value not visible? The first is in issue#42 and the second in issue#18. The last one (value not visible) is closed with a thanks for the feature request. The slider itself should be fixed in the 2.0.4 update of the app according to Athom.

**Comment by EdwardDumay** [comment]
I misread you an email you wrote. Sorry for bothering you. Thanks a lot for
your efforts.

Op wo 23 jan. 2019 18:15 schreef SailingDuck <notifications@github.com:

**Comment by SailingDuck** [comment]
Currently fixed this in 1.0.4.
