### ISSUE TITLE
Issues after update to 1.0.2. on V2

### ISSUE THREAD

**Issue by fvhuizen** [PatrickSannes/BetterLogic#36]
After updating to 1.0.2 it seems Homey is not triggering the **IF** card "**One of these variables changed**"
It works only when i manualy trigger the flows. The problems occured after i tried to make all variables in the standard Homey solution "Logic" but that wasn't working for me and Homey acted wrong. So i setup Better Logic again, did PTP afterwards because i missed the BL variables in the app settings. Ever since it doesn't trigger the function i mentioned. 

I also tried to replace logic cards, rebooted Better Logic a couple of times and PTP again some times.

**Comment by SailingDuck** [comment]
Can you show the card as you entered it? 
It needs to have the exact names in it separated with a comma. Tested this myself and seemed to work here:
![image](https://user-images.githubusercontent.com/23644634/51502903-961af000-1dd8-11e9-9ebd-af0f40a466b9.png)

**Comment by fvhuizen** [comment]
Dit e-mailadres is opgeheven.
This e-mail address is not available anymore.

**Comment by fvhuizen** [comment]
![img_8481](https://user-images.githubusercontent.com/25953849/51524827-3e5ba380-1e2f-11e9-93e7-b68e6fefa2b8.png)
This is not working in my case, but before the latest upgrade i did work.

**Comment by SailingDuck** [comment]
Don't think it worked as the underlying code tries to split at commas. Maybe it works if you add commas in between? Never tried this with tags actually 😄

**Comment by fvhuizen** [comment]
Yes you're right, no i typed it, it all works again. I will try it with tags and comma's again and see if that works.

**Comment by fvhuizen** [comment]
![img_8482](https://user-images.githubusercontent.com/25953849/51527417-b7112e80-1e34-11e9-931a-8ad44709e254.png)
This is not working either, so the only option is to type the tekst, better to remove the option to drop a tag. Or to make it working with tags.

**Comment by SailingDuck** [comment]
Thnx for notifying, I have to look what the input is with tags. Should be possible to get this to work I guess.

**Comment by fvhuizen** [comment]
thx, glad i found it because you point me the issue.
