### ISSUE TITLE
Feature Request - convert date time to epoch value

### ISSUE THREAD

**Issue by daneedk** [PatrickSannes/BetterLogic#4]
Would it be possible to creat an action card that takes the date and time tags from another card and calculates the epoch value from it and saves it as an numeric value? and would it be possible to also make a condition card that evaluates the current date time to a variable holding an epoch value?

I mean like this:
Set a epoch value:
![betterlogic](https://cloud.githubusercontent.com/assets/16610696/20836970/269e14d4-b8a2-11e6-9436-6a15d911aa9c.png)

Compare the current date time against an earlier stored (and possibly adjusted) epoch value:
![betterlogicand1](https://cloud.githubusercontent.com/assets/16610696/20837303/cdc9e99e-b8a3-11e6-9f2a-64be6eb0ab29.png)
or
![betterlogicand2](https://cloud.githubusercontent.com/assets/16610696/20837308/d11bfb32-b8a3-11e6-8441-4c266f5b6796.png)

Why do I ask this? Well, when I add 84600 to the value set at sunset I (almost) have the epoch value for half an our before sunset the next day.

**Comment by PatrickSannes** [comment]
This is already possible with the mathjs cards. In there there is a special
variable for the time now (epoch in seconds)

Would that be sufficient?

Groet

**Comment by daneedk** [comment]
Thanks, I've had a quick look but can't find what you mean. Can you explain, maybe with a screenshot, how to use it?

Thanks!

**Comment by PatrickSannes** [comment]
Create set card in mathjs (timenow takes amount of seconds sinse epoch)

[image: Inline image 1]


Then you can create any action card to trigger. Can't put mathjs in here,
but with a countdowntimer you can do something or with any other trigger.
Then in the when you can say:

[image: Inline image 2]

Hope it helps!

**Comment by daneedk** [comment]
Thanks, I have it working now, this is how I did it:

At sunset a flow saves the current date and time + 1 day into the epoSunset variable:

![betterlogic save timenow](https://cloud.githubusercontent.com/assets/16610696/20883572/30fe55d2-bae7-11e6-8acc-b2800a147440.png)

In another flow, which triggers when someone comes home, I check the current date and time against the epoSunset -1800 and when it's true I turn on some hue scenes.

![betterlogic evaluate timenow](https://cloud.githubusercontent.com/assets/16610696/20883615/706dab96-bae7-11e6-83ac-0039fc93958e.png)

These flows enables me to use an offset from sunset in a reliable way

Thanks again for this great app!!!

(Btw, the images in your post don't show up)
