### ISSUE TITLE
Better logic triggers stopped working with Homey 1.1.2.

### ISSUE THREAD

**Issue by peaoo** [PatrickSannes/BetterLogic#7]
Since the update the Flow triggers stopped working. I can see the variable changing in the settings screen (e.g. when toggled via REST Call) but the Flows aren't triggered. Another flow with Betterlogic in "...and..." as condition is working aswell. It seems that only the triggers are affected .

**Comment by glijie** [comment]
here the same app better logic stopt working after latest update 1.1.2. And so all my flows

**Comment by PatrickSannes** [comment]
Yep. Guess something went wrong. Ill contact athom to see what is going on.

**Comment by glijie** [comment]
thx

**Comment by peaoo** [comment]
Thank you.
I found out something new, the trigger seems to work with string variables but not with boolean. I changed a flow that used a boolean trigger "A variable changed" to a string variable with "true" and "false" and the flows worked again.

**Comment by PatrickSannes** [comment]
Numbers also don't work.

**Comment by PatrickSannes** [comment]
Fixed in 0.9.9. Though trigger drop tokens are removed.... Please see the forum for more details.
