### ISSUE TITLE
Feature request - Create device-type for a variable or BitFlip

### ISSUE THREAD

**Issue by WesRos** [PatrickSannes/BetterLogic#8]
To use the built-in voice comment it would be nice to label a variable or BitFlip device.
Labels:
- Light

- Temperature sensor

- Motion Sensor

I don't know with device type are used in Homey.

In the following discussion we had found this feature:
https://forum.athom.com/discussion/2285/domoticz-data

**Comment by PatrickSannes** [comment]
I'm trying to figure out how to add this. For now no clue, but when I do I try to add it ;) If you have any suggestions, please let me know.

**Comment by WesRos** [comment]
Maybe it's more a bigger thing. Another app: x10 has the same. The guy benotje in discussion: https://forum.athom.com/discussion/2285/domoticz-data had the same for a x10 device. He would change a x10 device to the device type: light/lamps/bulb??.

When there isn't a possibility for a App developer to switch a device to a device-type, I would made an Feature request for the Homey Core.
